### ISSUE TITLE
Mariadb install fails on RHEL 8 due to mariadb_service set to mysql

### ISSUE THREAD

**Issue by jeffcpullen** [diodonfrost/ansible-role-mariadb#2]
##### SUMMARY

Logic in the vars/RedHat.yml say that if the ansible major version isn't 7 then the service name should be mysql. This causes the install to fail and the variable can't be overridden with group_vars or with a var defined with the import_role. 

I am able to work around the issue by removing the logic to switch the mariadb_service from mysql

not working
```
mariadb_service: '{{ "mariadb"
                     if (ansible_distribution_major_version == "7")
                     else "mysql" }}'
```

working
```
mariadb_service: 'mariadb'
```
##### STEPS TO REPRODUCE

Using ansible version 2.9.2 against a RHEL 8.1 system

group_vars
```
install_from: os_repository
mariadb_version: 10.3
mariadb_database:
  - name: dbname
    state: present

# Need to submit bug for this (must be called at role import)
#mariadb_service: mariadb

mariadb_user:
  - name: dbuser
    host: '%'
    password: 'password'
    priv: '*.*:ALL'
    encrypted: false
disable_remote_root_login: false
mariadb_bind_address: '0.0.0.0'
mariadb_port: 3306
mariadb_slow_query_log_enabled: false
mariadb_slow_query_time: "2"

```

site.yml
```
- hosts: databasehost
  tasks:

    - name: Run mariadb install
      import_role:
        name: diodonfrost.mariadb
      vars:
        mariadb_service: mariadb

```

##### EXPECTED RESULTS

```
TASK [diodonfrost.mariadb : Mariadb service] **********************************************************
changed: [databasehost]

```

##### ACTUAL RESULTS

```
TASK [diodonfrost.mariadb : Mariadb service] **********************************************************
fatal: [databasehost]: FAILED! => {"changed": false, "msg": "Could not find the requested service mysql: host"}

```

##### ENVIRONMENT

Ansible 2.9.2
RHEL 8.1
